import pycyphal.application
from _typeshed import Incomplete
from pycyphal.transport import AlienTransfer as AlienTransfer, Timestamp as Timestamp
from typing import Any, Callable, Type

logger: Incomplete

class Iface:
    def __init__(self, node: pycyphal.application.Node) -> None: ...
    def add_trace_handler(self, cb: Callable[[Timestamp, AlienTransfer], None]) -> None: ...
    def add_transport_error_handler(self, cb: Callable[[pycyphal.transport.ErrorTrace], None]) -> None: ...
    def add_standard_subscription(self, dtype: Any) -> None: ...
    def try_request(self, dtype: Type[Any], server_node_id: int, request: Any) -> None: ...
